# @package _global_
model:
  charset_train: " ি ে ূ া ো ৈ ী ঁ ৌ ু ় ্ ং ঃ ৃচ২পসফড়ঔক৮ঐঋণ৪ঈঝযঠথতঙজঢ৯৬ওঘ১০খএ-ছবঢ়য়উলহডঅরশমষগ৷।ভৰঊআৎধৱইটন৭৩দঞ৫৳৵ৠঌ৶ৡ৺ঽ৻৴৸ঀ৲৹ "
  charset_test: " ি ে ূ া ো ৈ ী ঁ ৌ ু ় ্ ং ঃ ৃচ২পসফড়ঔক৮ঐঋণ৪ঈঝযঠথতঙজঢ৯৬ওঘ১০খএ-ছবঢ়য়উলহডঅরশমষগ৷।ভৰঊআৎধৱইটন৭৩দঞ৫৳৵ৠঌ৶ৡ৺ঽ৻৴৸ঀ৲৹ "


