# @package _global_
model:
  charset_train: "ি ৄ ু ৗ ো ৈ ৌ ঁ ৃ া ় ঃ ূ ে ং ী ্আৱ২৷দবঠম৬৺ঌখঘঢষউঋয৵ফচকঊরতঔঙইঞওণনভয়৴ট৪ৡথ০১ঀঝৠ৶ড়ঈলছ৮এ৸৲অৎজধগ৫ৰঽঢ়৳প৩ড৭৹শঐসহ৯৻ "
  charset_test: "ি ৄ ু ৗ ো ৈ ৌ ঁ ৃ া ় ঃ ূ ে ং ী ্আৱ২৷দবঠম৬৺ঌখঘঢষউঋয৵ফচকঊরতঔঙইঞওণনভয়৴ট৪ৡথ০১ঀঝৠ৶ড়ঈলছ৮এ৸৲অৎজধগ৫ৰঽঢ়৳প৩ড৭৹শঐসহ৯৻ "


