# @package _global_
model:
  charset_train: ' ા ૉ ૢ િ ઁ ી ો ૌ ૂ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટઢ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ '
  charset_test: ' ા ૉ ૢ િ ઁ ી ો ૌ ૂ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટઢ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ '


