# @package _global_
model:
  charset_train: "ા ૉ ૢ િ ઁ ી ો ૌ ૂ ૅ ુ ં ્ ઃ ૃ ે ૄ ઼ૈઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ "
  charset_test: "ા ૉ ૢ િ ઁ ી ો ૌ ૂ ૅ ુ ં ્ ઃ ૃ ે ૄ ઼ૈઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ "


