# @package _global_
model:
  charset_train: "् ः ॄ ऺ ॓ ॑ ँ ॅ ृ ़ ी ा ो ि ै ॔ ॣ े ु ॆ ं ौ ू ॉ ॊ ॖ ॢ ॒धभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑ "
  charset_test: "् ः ॄ ऺ ॓ ॑ ँ ॅ ृ ़ ी ा ो ि ै ॔ ॣ े ु ॆ ं ौ ू ॉ ॊ ॖ ॢ ॒धभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑ "


