# @package _global_
model:
  charset_train: " ्ःॄऺ॓॑ँॅृ़ीाोिै॔ॣेुॆंौूॉॊॖॢ॒ાૉૢિઁીોૌૂૅું્ઃૃેૄ઼ૈधभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ"
  charset_test: " ्ःॄऺ॓॑ँॅृ़ीाोिै॔ॣेुॆंौूॉॊॖॢ॒ાૉૢિઁીોૌૂૅું્ઃૃેૄ઼ૈधभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ"


