# @package _global_
model:
  charset_train: "ು  ಃೕೖೄೀೊೋೇಿ್ೈಂ಼ೆಾೂೃೌఁౄెౌొృూః్ంాౖుిోేీైೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯"
  charset_test: "ು  ಃೕೖೄೀೊೋೇಿ್ೈಂ಼ೆಾೂೃೌఁౄెౌొృూః్ంాౖుిోేీైೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯"


