# @package _global_
model:
  charset_train: "ು ಃ ೕ ೖ ೄ ೀ ೊ ೋ ೇ ಿ ್ ೈ ಂ ಼ ೆ ಾ ೂ ೃ ೌೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇ "
  charset_test: "ು ಃ ೕ ೖ ೄ ೀ ೊ ೋ ೇ ಿ ್ ೈ ಂ ಼ ೆ ಾ ೂ ೃ ೌೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇ "


