# @package _global_
model:
  charset_train: ' ೂ ು ೃ ಃ ೌ ೋ ೕ ೇ ೊ ೈ ೖ ೀ ೄ ೆ ್ ಾ ಼ ಿ ಂ ಁೲ ೢ ೣಀಪ೧೩೪ಧಒಆಞಣಽಈಗ೭ಯಉಛಖಏಚಓಫ೫ರಬ೦ಠಔಊಐಮಌಘ೬ತಭಜಋದಶಎನಕಇ೮೯ಅ೨ಸೠಷಟವಱಳಲಥೡಹಙೞಢಡಝೱೳ '
  charset_test: ' ೂ ು ೃ ಃ ೌ ೋ ೕ ೇ ೊ ೈ ೖ ೀ ೄ ೆ ್ ಾ ಼ ಿ ಂ ಁೲ ೢ ೣಀಪ೧೩೪ಧಒಆಞಣಽಈಗ೭ಯಉಛಖಏಚಓಫ೫ರಬ೦ಠಔಊಐಮಌಘ೬ತಭಜಋದಶಎನಕಇ೮೯ಅ೨ಸೠಷಟವಱಳಲಥೡಹಙೞಢಡಝೱೳ '


