# @package _global_
model:
  charset_train: "ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௗ ௌദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷ "
  charset_test: "ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௗ ௌദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷ "


