# @package _global_
model:
  charset_train: "ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟ "
  charset_test: "ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟ "


