# @package _global_
model:
  charset_train: "় ঁ ঃ ী ে ্ ু ি ং ৗ ৈ ো ৃ া ূ ৌঔদ২মযবএণ৪ঠছ।পউ৭ঐঘচজওষফঊ৯লআৎ৩শট১৫তখঝইঢগডঞৱ০৬ঋধঙ-৮করহয়ঈনথভঅড়স "
  charset_test: "় ঁ ঃ ী ে ্ ু ি ং ৗ ৈ ো ৃ া ূ ৌঔদ২মযবএণ৪ঠছ।পউ৭ঐঘচজওষফঊ৯লআৎ৩শট১৫তখঝইঢগডঞৱ০৬ঋধঙ-৮করহয়ঈনথভঅড়স "


