# @package _global_
model:
  charset_train: "় ꯭ ৗ꯬ ꯤ ꯨ ꯪ ꯦ ꯥ ꯩ ꯧ ঁꯣঃ꯵ꯋꯜꯒꯊꯌꯚ꯹ꯄꯗ꯴꯲ꯠ৺ꯎꯟꯇ꯷ꯅꯞ꯸ꯖꯓꯡꯆꯁꯝ꯫ꯙꯢ꯰꯶ꯈꯉꯛꯕꯐꯏꯀ꯳ꯍ꯱ꯔৠꯑꯂꯃꯘ "
  charset_test: "় ꯭ ৗ꯬ ꯤ ꯨ ꯪ ꯦ ꯥ ꯩ ꯧ ঁꯣঃ꯵ꯋꯜꯒꯊꯌꯚ꯹ꯄꯗ꯴꯲ꯠ৺ꯎꯟꯇ꯷ꯅꯞ꯸ꯖꯓꯡꯆꯁꯝ꯫ꯙꯢ꯰꯶ꯈꯉꯛꯕꯐꯏꯀ꯳ꯍ꯱ꯔৠꯑꯂꯃꯘ "


