# @package _global_
model:
  charset_train: " ଃ ୍ ି ା ୗ ୂ ୌ ଼ ୁ ୋ ଁ େ ୖ ୀ ୈ ୃ ଂ ୄ ୢ ୣହଋଌ୧ଫଢୠତ୨ବ୪ଞ୬ଣଭଡଵୱ୮ଔସଘଠନଥୟ୭ଝଧ୰ପଖଇରମଷଚ୫ଉଆଶଽଦଏଈଟଓ୯ଊୡକଯଅଐଜଳଲଙ୦୩ଛଗ୶୵୴୳୷ଡ଼୲ଢ଼ "
  charset_test: " ଃ ୍ ି ା ୗ ୂ ୌ ଼ ୁ ୋ ଁ େ ୖ ୀ ୈ ୃ ଂ ୄ ୢ ୣହଋଌ୧ଫଢୠତ୨ବ୪ଞ୬ଣଭଡଵୱ୮ଔସଘଠନଥୟ୭ଝଧ୰ପଖଇରମଷଚ୫ଉଆଶଽଦଏଈଟଓ୯ଊୡକଯଅଐଜଳଲଙ୦୩ଛଗ୶୵୴୳୷ଡ଼୲ଢ଼ "


