# @package _global_
model:
  charset_train: " ਃ ਂ ੂ ੍ ੱ ੋ ੵ ੈ ਾ ਿ ੑ ੌ ੰ ੁ ਁ ੇ ੀ ਼ੜਬਮਊਥ੩ਣਅਜਟਆਝੳਞਏਓਠਇ੯੦ਦਗਛਙਵਲਕ੬ਚ੧ਔਹ੨ਐੴਖਫਧ੪ਸਨਈਡ੫ੲ੭੮ਢਉਸ਼ਭਰਪਯਘਤਖ਼ਲ਼ਜ਼ਗ਼ਫ਼ "
  charset_test: " ਃ ਂ ੂ ੍ ੱ ੋ ੵ ੈ ਾ ਿ ੑ ੌ ੰ ੁ ਁ ੇ ੀ ਼ੜਬਮਊਥ੩ਣਅਜਟਆਝੳਞਏਓਠਇ੯੦ਦਗਛਙਵਲਕ੬ਚ੧ਔਹ੨ਐੴਖਫਧ੪ਸਨਈਡ੫ੲ੭੮ਢਉਸ਼ਭਰਪਯਘਤਖ਼ਲ਼ਜ਼ਗ਼ਫ਼ "


