# @package _global_
model:
  charset_train: "ௗ ொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௌஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷ "
  charset_test: "ௗ ொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௌஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷ "


