# @package _global_
model:
  charset_train: "ఁ ౄ ె ౌ ొ ృ ూ ః ్ ం ా ౖ ు ి ో ే ీ ైఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯ "
  charset_test: "ఁ ౄ ె ౌ ొ ృ ూ ః ్ ం ా ౖ ు ి ో ే ీ ైఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯ "


